name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # First job
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Say hi from job1
        run: echo "hi from job1"

  # Second job, runs after job1
  job2:
    runs-on: ubuntu-latest
    needs: job1   # this makes job2 wait for job1 to finish successfully
    steps:
      - uses: actions/checkout@v4

      - name: Say goodbye from job2
        run: echo "Goodbye from job2"
